# Table of Contents

1. [Project Setup](#project-setup)
2. [To-Do](#to-do)
3. [Books](#books)
    - [NYT Bestsellers API](#nyt-bestsellers)
    - [Google Books API](#google-books-api)
4. [Movies](#movies)
    - [IBMD Dataset](#imbd)
5. [Datasets](#datasets)
6. [Adjacency-Matrix](#adjacency-matrix)
6. [Current Impediments](#current-impediments)


## Project Setup

In [290]:
# Import libraries
import pandas as pd
import numpy as np
import requests
import json
from datetime import datetime, timedelta
import datetime
import re
import time
import itertools
from bs4 import BeautifulSoup

In [208]:
df_rachel = pd.read_csv(r"C:\Users\ralexander\Downloads\rachel_notion_recommender_engine.csv") # load user datset

In [209]:
# Book df
df_books = df_rachel[df_rachel['Type'].str.contains('Book')]
# Movie df
df_movie = df_rachel[df_rachel['Type'].str.contains('Movie')]
# TV Show df
df_tvshow = df_rachel[df_rachel['Type'].str.contains('TV Show')]

# df_books.head(50)

## To-Do

Working Idea 12/16: Pivoting to more of a genre classifier bc of difficulties accessing reliable book reviews

1. Fix NYT_bestsellers_24 error handling!
2. Get full year dataset NYT_bestsellers_24
3. Add genres using GB_genres_str_format function
4. Export full dataset as CSV
5. Graph genres of books
6. Build dataset Mojo_boxoffice_24 (you have the pieces, just put them together) -- CHECK
7. Find and incorporate movie genres!!
8. Graph genres of movies
9. Compare visuals of books and movies!

Sources
* https://medium.com/@kirudang/how-to-calculate-the-distance-for-categorical-data-application-of-jaccard-index-52a5bac7107

In [210]:
## subset top 10 of each category for text analytics
### text is applicable to books, movie and tb scripts, music lyrics, song titles

## text sentiment analysis
## text matching
## topic frequency

## start: topic frequency among book reviews

# what are the different features of text data that can apply to books and movies?

## Books

### NYT Bestsellers

In [240]:
# Define get book details function

def NYT_book_details(date, NYT_category):
    """
    Populate a pandas DataFrame with details on the NYT bestsellers of a given week for a particular genre

    Parameters:
    date: str format YYYY-MM-DD (Sunday). Reflects sales for week ending two weeks prior (Saturday)
    NYT_category: str of NYT accepted category. Formatted with spaces replaced by hyphens.

    Returns:
    a populated pandas DataFrame
    """
    
    # Initialize list containers for book details
    title_lst = []
    author_lst = []
    summary_lst = []
    isbn10_lst = []
    isbn13_lst = []

    # Authorize NYT Bestsellers API
    api = f'https://api.nytimes.com/svc/books/v3/lists/{date}/{NYT_category}.json?&api-key=B6sstxBJ39IKPTsYZA72UGVPhBGymY7G'
    response = requests.get(api)
    data = response.json()

    # Check if api call retrieves results
    # if data['results'] != []:

    # Populate lists of book details
    try:
        for i in range(0, len(data["results"])):
            title_lst.append(json.dumps(data['results']['books'][i]['title'], indent=4, sort_keys=True)) # title
            author_lst.append(json.dumps(data['results']['books'][i]['author'], indent=4, sort_keys=True)) # author
            summary_lst.append(json.dumps(data['results']['books'][i]['description'], indent=4, sort_keys=True)) # summary
            isbn10_lst.append(json.dumps(data['results']['books'][i]['primary_isbn10'], indent=4, sort_keys=True)) # isbn10
            isbn13_lst.append(json.dumps(data['results']['books'][i]['primary_isbn13'], indent=4, sort_keys=True)) # isbn13

            # Create DataFrame
            book_details_dict = {
                'title': title_lst
                , 'author': author_lst
                , 'summary': summary_lst
                , 'isbn10': isbn10_lst
                , 'isbn13': isbn13_lst
            }

            book_details_df = pd.DataFrame(book_details_dict)

            book_details_df['title'] = book_details_df['title'].str.strip('"')
            book_details_df['author'] = book_details_df['author'].str.strip('"')
            book_details_df['summary'] = book_details_df['summary'].str.strip('"')
            book_details_df['isbn10'] = book_details_df['isbn10'].str.strip('"')
            book_details_df['isbn13'] = book_details_df['isbn13'].str.strip('"')

            sales_ending_week = datetime.datetime.strptime(date, "%Y-%m-%d") - timedelta(days=15) # calcuate date of week when sales end
                
            book_details_df['sales_ending_week'] = sales_ending_week.strftime("%Y-%m-%d")
            book_details_df['NYT_category'] = NYT_category
            # except AttributeError:
            #     pass
    
    except KeyError as KE:
        raise KE
    #except data["results"] == []:
        

    return book_details_df

In [241]:
# Get full list of NYT categories
api = f'https://api.nytimes.com/svc/books/v3/lists/names.json?&api-key=B6sstxBJ39IKPTsYZA72UGVPhBGymY7G'
response = requests.get(api)
data = response.json()

for i in range(0, len(data["results"])):
    print(data["results"][i]["list_name_encoded"])
    #print(type(x))
# there are 58 categories

combined-print-and-e-book-fiction
combined-print-and-e-book-nonfiction
hardcover-fiction
hardcover-nonfiction
trade-fiction-paperback
mass-market-paperback
paperback-nonfiction
e-book-fiction
e-book-nonfiction
hardcover-advice
paperback-advice
advice-how-to-and-miscellaneous
hardcover-graphic-books
paperback-graphic-books
manga
combined-print-fiction
combined-print-nonfiction
chapter-books
childrens-middle-grade
childrens-middle-grade-e-book
childrens-middle-grade-hardcover
childrens-middle-grade-paperback
paperback-books
picture-books
series-books
young-adult
young-adult-e-book
young-adult-hardcover
young-adult-paperback
animals
audio-fiction
audio-nonfiction
business-books
celebrities
crime-and-punishment
culture
education
espionage
expeditions-disasters-and-adventures
fashion-manners-and-customs
food-and-fitness
games-and-activities
graphic-books-and-manga
hardcover-business-books
health
humor
indigenous-americans
relationships
mass-market-monthly
middle-grade-paperback-monthly
pape

In [242]:
# Concat books for every day/genre combination for a given time frame

NYT_bestsellers_24 = pd.DataFrame()

# Get list of NYT cateogries
api = f'https://api.nytimes.com/svc/books/v3/lists/names.json?&api-key=B6sstxBJ39IKPTsYZA72UGVPhBGymY7G'
response = requests.get(api)
data = response.json()

# Initialize timeframe dates
# ONE MONTH OF DATA TAKES APPROX FIVE MINUTES TO RUN 
week_date_counter = '2024-12-01'
week_dttm_counter = datetime.datetime.strptime(week_date_counter, '%Y-%m-%d')

sunday_end_date = '2024-12-01'
sunday_end_dttm = datetime.datetime.strptime(sunday_end_date, '%Y-%m-%d')

error_dict = {
}

sleep_time = 45 # seconds

# Run function
while week_dttm_counter <= sunday_end_dttm:
    week_date_counter = week_dttm_counter.strftime('%Y-%m-%d')
    print(week_date_counter)
    for i in range(0, len(data['results'])): # iterate through each genre
        print(data['results'][i]['list_name_encoded'])
        try:
            NYT_bestsellers_24 = pd.concat([NYT_bestsellers_24, NYT_book_details(week_date_counter, data['results'][i]['list_name_encoded'])], ignore_index=True) # add to dataframe
        except KeyError: # base exception error would catch all errors
            date_str = week_date_counter
            if date_str in error_dict:
                error_dict[date_str].append(data['results'][i]['list_name_encoded'])
            else:
                error_dict = {date_str: [data['results'][i]['list_name_encoded']]}
    week_dttm_counter = datetime.datetime.strptime(week_date_counter, "%Y-%m-%d") + timedelta(weeks=1)
    time.sleep(sleep_time)
    print("--------------------------------------------------------------------------------------------") # young-adult-paperback-monthly is the last genre


print("loop complete")

2024-12-01
combined-print-and-e-book-fiction
combined-print-and-e-book-nonfiction
hardcover-fiction
hardcover-nonfiction
trade-fiction-paperback
mass-market-paperback
paperback-nonfiction
e-book-fiction
e-book-nonfiction
hardcover-advice
paperback-advice
advice-how-to-and-miscellaneous
hardcover-graphic-books
paperback-graphic-books
manga
combined-print-fiction
combined-print-nonfiction
chapter-books
childrens-middle-grade
childrens-middle-grade-e-book
childrens-middle-grade-hardcover
childrens-middle-grade-paperback
paperback-books
picture-books
series-books
young-adult
young-adult-e-book
young-adult-hardcover
young-adult-paperback
animals
audio-fiction
audio-nonfiction
business-books
celebrities
crime-and-punishment
culture
education
espionage
expeditions-disasters-and-adventures
fashion-manners-and-customs
food-and-fitness
games-and-activities
graphic-books-and-manga
hardcover-business-books
health
humor
indigenous-americans
relationships
mass-market-monthly
middle-grade-paperback-m

In [ ]:
# print(week_date_counter)
# week_date_counter = datetime.datetime.strptime(week_date_counter, "%Y-%m-%d") + timedelta(weeks=1)

In [243]:
len(NYT_bestsellers_24)

48

In [244]:
error_dict

{'2024-12-01': ['trade-fiction-paperback',
  'mass-market-paperback',
  'paperback-nonfiction',
  'e-book-fiction',
  'e-book-nonfiction',
  'hardcover-advice',
  'paperback-advice',
  'advice-how-to-and-miscellaneous',
  'hardcover-graphic-books',
  'paperback-graphic-books',
  'manga',
  'combined-print-fiction',
  'combined-print-nonfiction',
  'chapter-books',
  'childrens-middle-grade',
  'childrens-middle-grade-e-book',
  'childrens-middle-grade-hardcover',
  'childrens-middle-grade-paperback',
  'paperback-books',
  'picture-books',
  'series-books',
  'young-adult',
  'young-adult-e-book',
  'young-adult-hardcover',
  'young-adult-paperback',
  'animals',
  'audio-fiction',
  'audio-nonfiction',
  'business-books',
  'celebrities',
  'crime-and-punishment',
  'culture',
  'education',
  'espionage',
  'expeditions-disasters-and-adventures',
  'fashion-manners-and-customs',
  'food-and-fitness',
  'games-and-activities',
  'graphic-books-and-manga',
  'hardcover-business-books',

In [245]:
# NYT_book_details("2024-12-01", "trade-fiction-paperback") # this sometimes works, sometime's doesnt!!

# Examine api response called within function:

api = f'https://api.nytimes.com/svc/books/v3/lists/{'2024-12-01'}/{'paperback-business-books'}.json?&api-key=B6sstxBJ39IKPTsYZA72UGVPhBGymY7G'
response = requests.get(api)
data = response.json()
data

{'status': 'ERROR',
 'copyright': 'Copyright (c) 2025 The New York Times Company.  All Rights Reserved.',
 'errors': ['No list found for list name and/or date provided.', 'Not Found'],
 'results': []}

### Google Books API

In [249]:
api = f'https://www.googleapis.com/books/v1/volumes?q=' + '9781649377371' + '&key=AIzaSyDeDHz_ZcyfbMjqKxFFzScDP5cyLa-u4w8' # IS Volume ID the correct parameter?

response = requests.get(api)
data = response.json()
data
# items = data.get('items')[0]
# print(items.get('selfLink'))

# OK GOOGLE BOOKS HAS SOME OF THE ISBNS COMPLETELY WRONG!! what do do about this?

# 9781638932239 --> should be Lights Out
# 9780593312070 --> should be The Frozen River
# 9781649377371 --> Fourth Wing
# 9780593655030 --> the Anxious Generation 


# mismatches are likely missing from Google Books entirely.  

{'kind': 'books#volumes',
 'totalItems': 1825,
 'items': [{'kind': 'books#volume',
   'id': 'cAZaEAAAQBAJ',
   'etag': 'uTw3HUPA4qQ',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/cAZaEAAAQBAJ',
   'volumeInfo': {'title': 'Conversation of the Three Wayfarers',
    'authors': ['Peter Weiss'],
    'publisher': 'New Directions Publishing',
    'publishedDate': '2022-04-26',
    'description': 'This fast-moving, tightly-wound, and gleefully dark novella contains an entire universe in miniature Conversation of the Three Wayfarers is a tale overheard, rather than told directly. Abel, Babel, and Cabel, the wayfarers, carry on a three-sided monologue, each reporting curious incidents—the effect is of three capers rolled into one: a steeplechase performed on a floating pontoon. But are they really three distinct individuals? Why do their lives blend in such a fantastic manner? Weiss’s strikingly original prose has an impossibly contained quality, with each sentence doing a perfect

In [97]:
# data['items']#[0]['volumeInfo']['averageRating'] # if averageRating exists it will be here
# canoncial volume link webpage has genres listed

In [250]:
def GB_genres_format_str(isbn13):
    """
    Get genres for a particular book from the Google Books API and transform string values as a list

    Parameters:
    isbn13: isbn13 string of a book

    Returns:
    list of unique genres associated to that book
    """

    api = f'https://www.googleapis.com/books/v1/volumes?q=' + isbn13 + '&key=AIzaSyDeDHz_ZcyfbMjqKxFFzScDP5cyLa-u4w8'
    response = requests.get(api)
    data = response.json()
    # print(data.keys())

    items = data.get('items')[0] # dict, ERROR: Nonetype object is not scriptable 
    selfLink = items.get('selfLink')
    
    intermediate_genres_lst = []
    fact_genres_lst = []

    r = requests.get(selfLink)
    d = r.json() # dict
    vol_info = d.get('volumeInfo') # dict
    genres = vol_info.get('categories')

    for genre in genres:
    # print(genre) # contains "/"
        genre_lst = re.split(' / ', genre)
        for i in genre_lst:
            intermediate_genres_lst.append(i.lower())
    
    genres_unique = list(set(intermediate_genres_lst))

    # Handle use cases where a comma-seperated list is contained in a single string object
    for u in genres_unique:
        for i in re.split(',', u):
            fact_genres_lst.append(i.lstrip())
            
    return fact_genres_lst

In [251]:
# for i in range(len(NYT_bestsellers_24)):
#     print(NYT_bestsellers_24.loc[i, 'isbn13'])
#     genres = GB_genres_format_str(NYT_bestsellers_24.loc[i, 'isbn13'])
#     print(genres)
#     time.sleep(3) # TEST 3 seconds between each row

# Nope, that didn't work. Try running this operation in batches?

In [252]:
# batch processing 

batch_size = 20 # tried: 10, 20, 40, *50
NYT_error_df = pd.DataFrame()

GB_genres_lst = []

for i in range(0, len(NYT_bestsellers_24), batch_size):
    NYT_batch_df = NYT_bestsellers_24[i:i + batch_size] # store df slice
    batch_index = NYT_batch_df.index.tolist()
    # iterate through each row of the chunk df
    for i in batch_index:
        isbn = NYT_batch_df.loc[i,'isbn13']
        # print(isbn)
        try:
            GB_genres_lst.append(GB_genres_format_str(isbn))
        except TypeError:
            print("we have a type error")
            print(i)
            print(isbn)
            isbn = NYT_batch_df.loc[i, 'isbn10'] # THE MINUTE I UNCOMMENT THIS LINE IT BREAKS AND I DON'T UNDERSTAND WHY
            GB_genres_lst.append(GB_genres_format_str(isbn))
    time.sleep(12) # tried: 15, 30, 45, *60 seconds

NYT_bestsellers_24['GB_genres'] = GB_genres_lst

we have a type error
26
9781649374172


## Movies

In [253]:
# Get Box Office Movies from Box Office Mojo
    # Domestic Box Office bc NYT Bestsellers refers to bestsellers in the United States
# Get genre information from IMDb non-commerical datasets: https://developer.imdb.com/non-commercial-datasets/

In [134]:
url='https://www.boxofficemojo.com/weekend/by-year/2021/'
req=requests.get(url) # make the request
content=req.text
soup=BeautifulSoup(content)
rows=soup.findAll('tr') # tabular data is stored under the "tr" tag
for row in rows:
    data = row.findAll('td')

In [ ]:
for i in range(1, 6):
    print(i)
    row = rows[i]
    data = row.findAll('td')
    print(data[0])

# data = rows[0] #findall searches for a regex
# data

In [ ]:
url='https://www.boxofficemojo.com/weekly/2024W50/?ref_=bo_wly_table_1'
req=requests.get(url) # make the request
content=req.text

soup=BeautifulSoup(content)
rows=soup.findAll('tr') # tabular data is stored under the "tr" tag

rows_indexes = [2, 3, 5, 6, 8, 10] 

for i in range(1, len(rows)):
    data = rows[i].findAll('td')
    #for j in rows_indexes:
        #print(j)
    print(data[2].text)
    # range(len(data)):
    # print(data)
    print("--------------------------")

In [ ]:
for i in range(1, 6):
    print(i)
    data = rows[i].findAll('td')
    data_a = data[2].findAll('a', href=True)
    print('https://www.boxofficemojo.com/'+data_a[0]['href'])
    #print(data[2].text)

In [ ]:
# NYT_bestsellers_24: Sales_ending_week

# Movie Title
# Sales_endind_week (Thursday date of the given week bc that's when sales technically end?) Thursday, Jan 4, 2024
# Distributor (author equivalent)
# Theaters (new, no equivalent in NYT_bestsellers_24)
# Gross (new, no equivalent in NYT_bestsellers_24)

# Missing - Summary

# https://www.boxofficemojo.com/release/rl862748673/?ref_=bo_wl_table_1


In [ ]:
# Extract movie summary

url='https://www.boxofficemojo.com//release/rl259556097/?ref_=bo_wl_table_3'
req=requests.get(url) # make the request
content=req.text
soup=BeautifulSoup(content)
rows=soup.findAll('p')
rows[0].text

In [254]:
def Mojo_movie_details(week_url):
    """
    Get box office movie details for a particular week

    Parameters:
    Box Office Mojo string url for a particular week in the year 2024. Example: "https://www.boxofficemojo.com/weekly/2024W[#]/?ref_=bo_wly_table_1"

    Returns:
    A dataframe for all the box office movies of a particular week.
    """
    
     # Initialize list containers for movie details
    title_lst = []
    distributor_lst = []
    summary_lst = []
    theaters_count_lst = []
    week_gross_lst = []
    total_gross_lst= []

    # Initialize Box Office Mojo url
    url=week_url
    req=requests.get(url) # make the request
    content=req.text
    
    soup=BeautifulSoup(content)
    rows=soup.findAll('tr') # tabular data is stored under the "tr" tag

    # Populate lists of movie details
    for i in range(1, len(rows)): # skip header row
        data = rows[i].findAll('td')
        # Hard coded data extraction. Is there a more flexible way to do this?
        title_lst.append(data[2].text)
        week_gross_lst.append(data[3].text)
        theaters_count_lst.append(data[5].text)
        total_gross_lst.append(data[8].text)
        distributor_lst.append(data[10].text)

        # summary details
        data_a = data[2].findAll('a', href=True)
        summary_url = 'https://www.boxofficemojo.com/'+data_a[0]['href']

        summary_req=requests.get(summary_url) # make the request
        summary_content=summary_req.text
        summary_soup=BeautifulSoup(summary_content)
        summary_rows=summary_soup.findAll('p')
        summary_lst.append(summary_rows[0].text)

    # Create DataFrame
    movie_details_dict = {
        'title': title_lst
        , 'distributor': distributor_lst
        , 'summary': summary_lst
        , 'theaters_count': theaters_count_lst
        , 'week_gross': week_gross_lst
        , 'total_gross': total_gross_lst
         }

    movie_details_df = pd.DataFrame(movie_details_dict)

    movie_details_df['distributor'] = movie_details_df['distributor'].str.strip()

    return movie_details_df
    

In [255]:
Mojo_movie_details('https://www.boxofficemojo.com/weekly/2024W25/?ref_=bo_wly_table_1')

title  \
0                                        Inside Out 2   
1                               Bad Boys: Ride or Die   
2                                      The Bikeriders   
3                                  The Garfield Movie   
4                   Kingdom of the Planet of the Apes   
..                                                ...   
66                        School of Magical Animals 2   
67                                       We Grown Now   
68                    Household Saints2024 Re-release   
69                                               Solo   
70  The Feeling That the Time for Doing Something ...   

                            distributor  \
0   Walt Disney Studios Motion Pictures   
1               Sony Pictures Releasing   
2                        Focus Features   
3               Sony Pictures Releasing   
4                  20th Century Studios   
..                                  ...   
66               Blue Fox Entertainment   
67              Sony Pictures Releasing   
68                          Kino Lorber   
69                      Music Box Films   
70                    Magnolia Pictures   

                                              summary theaters_count  \
0   A sequel that features Riley entering puberty ...          4,440   
1   When their late police captain gets linked to ...          3,781   
2   After a chance encounter, headstrong Kathy is ...          2,642   
3   After Garfield's unexpected reunion with his l...          3,013   
4   Many years after the reign of Caesar, a young ...          2,410   
..                                                ...            ...   
66  The students of the school of magical animals ...              1   
67  Two young boys, best friends Malik and Eric, d...              2   
68  Unsettling drama about three generations of It...              2   
69  Follows Simon, who must deal with the disappoi...              1   
70  A mosaic-style comedy following the life of a ...              2   

      week_gross   total_gross  
0   $156,722,927  $411,906,043  
1    $26,779,125  $154,915,016  
2    $12,904,765   $12,904,765  
3     $6,097,768   $87,640,019  
4     $5,580,477  $166,376,566  
..           ...           ...  
66          $740       $45,603  
67          $569      $296,535  
68          $515       $38,101  
69          $370       $13,369  
70          $225       $82,083  

[71 rows x 6 columns]

In [256]:
Mojo_box_office_24 = pd.DataFrame()

sales_ending_week = '2024-01-04'

# Consider telling it to retry if it times out. 
# https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request
# Set max retries with HTTP adapter 

for i in range(1, 53):
    i_str = str(i)
    if i < 10:
        i_str = "0" + i_str
    week_url = 'https://www.boxofficemojo.com/weekly/2024W' + i_str + '/?ref_=bo_wly_table_1'
    # Get box office details for a particular week
    week_df = Mojo_movie_details(week_url=week_url)
    # Add new column for box office sales ending date
    # increment sales_ending_week var
    sales_ending_week = datetime.datetime.strptime(sales_ending_week, "%Y-%m-%d")  + timedelta(days=7)
    week_df['sales_ending_week'] = sales_ending_week.strftime("%Y-%m-%d")
    Mojo_box_office_24 = pd.concat([Mojo_box_office_24, week_df])
    print("week" + i_str + " is done")


week01 is done
week02 is done
week03 is done
week04 is done
week05 is done
week06 is done
week07 is done
week08 is done
week09 is done
week10 is done
week11 is done
week12 is done
week13 is done
week14 is done
week15 is done
week16 is done
week17 is done
week18 is done
week19 is done
week20 is done
week21 is done
week22 is done
week23 is done
week24 is done
week25 is done
week26 is done
week27 is done
week28 is done
week29 is done
week30 is done
week31 is done
week32 is done
week33 is done
week34 is done
week35 is done
week36 is done
week37 is done
week38 is done
week39 is done
week40 is done
week41 is done
week42 is done
week43 is done
week44 is done
week45 is done
week46 is done
week47 is done
week48 is done
week49 is done
week50 is done
week51 is done
week52 is done


In [ ]:
# Experimenting with datetime objects

# date = '2024-01-11'
# sales_ending_week = datetime.datetime.strptime(date, "%Y-%m-%d")  + timedelta(days=7)
# sales_ending_week.strftime("%Y-%m-%d")

## Datasets

In [373]:
NYT_bestsellers_24.head(25)

title                               author  \
0                        TO DIE FOR                       David Baldacci   
1                       FOURTH WING                       Rebecca Yarros   
2                         THE WOMEN                       Kristin Hannah   
3                     THE BOYFRIEND                      Freida McFadden   
4       A COURT OF THORNS AND ROSES                        Sarah J. Maas   
5                     THE HOUSEMAID                      Freida McFadden   
6                       IN TOO DEEP           Lee Child and Andrew Child   
7   HOW MY NEIGHBOR STOLE CHRISTMAS                         Meghan Quinn   
8                             JAMES                     Percival Everett   
9                        LIGHTS OUT                        Navessa Allen   
10                 THE FROZEN RIVER                         Ariel Lawhon   
11                           WICKED                      Gregory Maguire   
12                          MELANIA                        Melania Trump   
13                       ON TYRANNY                       Timothy Snyder   
14                  HILLBILLY ELEGY                             JD Vance   
15                           FRAMED       John Grisham and Jim McCloskey   
16              THE WAR ON WARRIORS                         Pete Hegseth   
17           THE ANXIOUS GENERATION                       Jonathan Haidt   
18     REVENGE OF THE TIPPING POINT                     Malcolm Gladwell   
19       CONFRONTING THE PRESIDENTS      Bill O'Reilly and Martin Dugard   
20   BE READY WHEN THE LUCK HAPPENS                           Ina Garten   
21   FROM HERE TO THE GREAT UNKNOWN  Lisa Marie Presley and Riley Keough   
22                      THE MESSAGE                     Ta-Nehisi Coates   
23         THE BODY KEEPS THE SCORE                  Bessel van der Kolk   
24                       TO DIE FOR                       David Baldacci   

                                              summary      isbn10  \
0   The third book in the 6:20 Man series. Devine ...  1538757931   
1   Violet Sorrengail is urged by the commanding g...  1649377371   
2   In 1965, a nursing student follows her brother...  1250178630   
3   A series of recent deaths causes Sydney Shaw t...  1728296226   
4   After killing a wolf in the woods, Feyre is ta...  1635575567   
5   Troubles surface when a woman looking to make ...  1538742578   
6   The 29th book in the Jack Reacher series. Reac...  0593725808   
7   A fake relationship and a Christmas contest ma...  1464230153   
8   A reimagining of \u201cAdventures of Huckleber...  0385550367   
9   As Aly and Josh live out their dark fantasies,...  1638932239   
10  In Maine, 1789, a midwife seeks to uncover the...  0593312074   
11  A misunderstood girl named Elphaba is declared...  0062852841   
12  The former and future first lady describes her...  1510782699   
13  Twenty lessons from the 20th century about the...  0804190119   
14  The vice president-elect, in a memoir written ...  0062300555   
15  Our criminal justice system viewed through the...  0385550448   
16  The former \"Fox & Friends Weekend\" host shar...  0063389428   
17  A co-author of \u201cThe Coddling of the Ameri...  0593655036   
18  Through a series of stories, Gladwell explicat...  0316575801   
19  The conservative commentator evaluates the leg...  125034641X   
20  A memoir by the cookbook author and Food Netwo...  0593799895   
21  Presley\u2019s memoir, completed by her daught...  0593733878   
22  The author of \u201cBetween the World and Me\u...  0593230388   
23  How trauma affects the body and mind, and inno...  0143127748   
24  The third book in the 6:20 Man series. Devine ...  1538757907   

           isbn13 sales_ending_week                          NYT_category  \
0   9781538757932        2024-11-16     combined-print-and-e-book-fiction   
1   9781649377371        2024-11-16     combined-print-and-e-book-fiction   
2   9781250178633        20

In [ ]:
# GB_genres_format_str('9781638932239')

In [258]:
Mojo_box_office_24.tail()

title            distributor  \
85              Day of the Fight  Falling Forward Films   
86                   Lake George      Magnolia Pictures   
87  The Sacrifice2024 Re-release            Kino Lorber   
88   Ernest Cole: Lost and Found      Magnolia Pictures   
89            Daytime Revolution            Kino Lorber   

                                              summary theaters_count  \
85  Follows a once renowned boxer as he takes a re...              1   
86  Two misfit oddballs embark on a road trip, str...              1   
87  At the dawn of World War III, a man searches f...              1   
88  Follows Ernest Cole's journey as the first Bla...              3   
89  Mike Douglas takes a week off and John Lennon ...              1   

   week_gross total_gross sales_ending_week  
85     $1,194     $73,482        2024-01-11  
86     $1,180     $14,137        2024-01-11  
87       $991     $94,519        2024-01-11  
88       $952     $37,328        2024-01-11  
89       $728     $35,750        2024-01-11

## Adjacency Matrix

In [439]:
# Initialize adjacency matrix

vertices_idx_df = pd.DataFrame(pd.Series(NYT_bestsellers_24['GB_genres'])).explode('GB_genres') # retain index values from NYT_bestsellers_24

vertices_ref_df = pd.DataFrame({'GB_genres':vertices_idx_df['GB_genres'].unique()}) # filter unique genres
vertices_ref_df['GB_genres_dummy'] = range(1, len(vertices_ref_df) + 1) # add dummy values
        
# Number of vertices
n = len(vertices_ref_df)
print(n)

adj_matrix = np.zeros((n, n), dtype=int)
print(adj_matrix)

154
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [444]:
#vertices_idx_df['NYT_bestsellers_24_index'] = vertices_idx_df.index
vertices_idx_df

GB_genres
0                  fiction
0                    crime
0      mystery & detective
0        police procedural
0                 suspense
..                     ...
47     juvenile nonfiction
47          activity books
47  interactive adventures
47                 animals
47                 general

[372 rows x 1 columns]

In [445]:
replacement_dict = vertices_ref_df.set_index('GB_genres')['GB_genres_dummy'].to_dict()
print("\nReplacement dictionary:")
print(replacement_dict)


Replacement dictionary:
{'fiction': 1, 'crime': 2, 'mystery & detective': 3, 'police procedural': 4, 'suspense': 5, 'thrillers': 6, 'action & adventure': 7, 'germany': 8, 'absurdist': 9, 'world literature': 10, '20th century': 11, 'classics': 12, 'women': 13, 'feminist': 14, 'world war i': 15, 'historical': 16, 'family life': 17, 'psychological': 18, 'literary': 19, 'general': 20, 'epic': 21, 'fantasy': 22, 'romance': 23, 'paranormal': 24, 'contemporary': 25, 'christian': 26, 'military': 27, 'erotic': 28, 'fairy tales': 29, 'folk tales': 30, 'legends & mythology': 31, 'espionage': 32, 'hard-boiled': 33, 'cozy': 34, 'international crime & mystery': 35, 'animals': 36, 'culinary': 37, 'business & economics': 38, 'workplace culture': 39, 'business ethics': 40, 'interest': 41, 'transgender': 42, 'lgbtq+': 43, 'coming of age': 44, 'sagas': 45, 'dark fantasy': 46, 'political': 47, 'adaptations & pastiche': 48, 'country & bluegrass': 49, 'entertainment & performing arts': 50, 'music': 51, 'ge

In [449]:
edges_lsts = []
for genre_lst in NYT_bestsellers_24['GB_genres']:
    updated_list = [replacement_dict.get(item, item) for item in genre_lst]
    edges = [(a, b) for a, b in itertools.product(updated_list, repeat=2) if a != b] # initialize for edges calculation
    edges_lsts.append(edges)

In [450]:
edges_lsts

[[(1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (2, 1),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (3, 1),
  (3, 2),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (4, 1),
  (4, 2),
  (4, 3),
  (4, 5),
  (4, 6),
  (4, 7),
  (5, 1),
  (5, 2),
  (5, 3),
  (5, 4),
  (5, 6),
  (5, 7),
  (6, 1),
  (6, 2),
  (6, 3),
  (6, 4),
  (6, 5),
  (6, 7),
  (7, 1),
  (7, 2),
  (7, 3),
  (7, 4),
  (7, 5),
  (7, 6)],
 [(1, 8),
  (1, 9),
  (1, 10),
  (1, 11),
  (1, 12),
  (8, 1),
  (8, 9),
  (8, 10),
  (8, 11),
  (8, 12),
  (9, 1),
  (9, 8),
  (9, 10),
  (9, 11),
  (9, 12),
  (10, 1),
  (10, 8),
  (10, 9),
  (10, 11),
  (10, 12),
  (11, 1),
  (11, 8),
  (11, 9),
  (11, 10),
  (11, 12),
  (12, 1),
  (12, 8),
  (12, 9),
  (12, 10),
  (12, 11)],
 [(13, 1),
  (13, 14),
  (13, 15),
  (13, 11),
  (13, 16),
  (1, 13),
  (1, 14),
  (1, 15),
  (1, 11),
  (1, 16),
  (14, 13),
  (14, 1),
  (14, 15),
  (14, 11),
  (14, 16),
  (15, 13),
  (15, 1),
  (15, 14),
  (15, 11),
  (15, 16),
  (11, 13),
  (1

In [452]:
for edge_lst in edges_lsts:
    for edge in edge_lst:
        i, j = edge[0], edge[1]
        adj_matrix[i, j] = 1
        adj_matrix[j, i] = 1
        # print(i, j)

print(adj_matrix)

IndexError: index 154 is out of bounds for axis 1 with size 154

In [327]:
for genre_lst in NYT_bestsellers_24["GB_genres"]:
    # Coordinate pair combinations per row, exclude pairs of identical elements
    # edges = [(a, b) for a, b in itertools.product(genre_lst, repeat=2) if a != b] # initialize for edges calculation
    for genre in genre_lst:
        # vertices.append(genre)
        print(genre)
        # match = edges_df[edges_df['GB_genres'] == genre]
        # print(match)

fiction
crime
mystery & detective
police procedural
suspense
thrillers
action & adventure
fiction
germany
absurdist
world literature
20th century
classics
women
fiction
feminist
world war i
20th century
historical
family life
fiction
mystery & detective
psychological
literary
general
thrillers
suspense
epic
fantasy
fiction
romance
paranormal
contemporary
fiction
christian
military
suspense
thrillers
action & adventure
fiction
military
suspense
thrillers
action & adventure
erotic
fantasy
fiction
romance
contemporary
fairy tales
folk tales
legends & mythology
general
fiction
crime
espionage
hard-boiled
mystery & detective
cozy
police procedural
paranormal
international crime & mystery
animals
historical
culinary
thrillers
suspense
business & economics
workplace culture
business ethics
interest
fiction
transgender
lgbtq+
coming of age
thrillers
suspense
sagas
epic
fantasy
fiction
dark fantasy
paranormal
contemporary
literary
coming of age
political
fairy tales
folk tales
legends & mytholo

In [455]:
# Example list of edges (assuming vertices are labeled by integers 0 through n-1)
edges = [(0, 1), (1, 2), (2, 3), (3, 0), (0, 2)]

# Identify all unique vertices
vertices = set()
for edge in edges:
    vertices.update(edge)
print(vertices)

# Mapping vertices to indices
vertex_list = sorted(vertices)  # Ensure consistent ordering
# vertex_list
vertex_index = {vertex: idx for idx, vertex in enumerate(vertex_list)}
print(vertex_index)

# Number of vertices
n = len(vertex_list)

# Initialize adjacency matrix
adj_matrix = np.zeros((n, n), dtype=int)
print(adj_matrix)

# vertex_index[edge[0]]

# # Fill adjacency matrix
for edge in edges:
    i, j = vertex_index[edge[0]], vertex_index[edge[1]]
    # print(i, j)
    adj_matrix[i, j] = 1
    adj_matrix[j, i] = 1  # Because the graph is undirected

# print("Adjacency Matrix:")
print(adj_matrix)

# # If you prefer a binary matrix, i.e. with 'int' type:
# adj_matrix = adj_matrix.astype(int)

{0, 1, 2, 3}
{0: 0, 1: 1, 2: 2, 3: 3}
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 1 1]
 [1 0 1 0]
 [1 1 0 1]
 [1 0 1 0]]


## Current Impediments

In [102]:
# Problems 1/13:

# I am trying to use batch processing to pull the genres. It's not working and I'm not sure why.
# I'm still in the process of tweaking the sleep timers. Currently it takes 5 minutes for me to call the best sellers for 1 month.
# Can't install BeautifulSoup

## Notes on Genre Classifiers:

Genre based network in which every node is a book genre. Edge weight would be number of books who have both genres.

*Betweenness* centrality measures the extent to which a vertex lies on a path between other vertices
    High betweeness -- control of information passing
    assumes: 
    
    1) every pair of vertices exchange information with equal probability 
    
    2) information flows along the shortest path between two vertices. But information doesn't always take the shortest route! 